### ISSUE TITLE
Multiple Radial Gradients on a single node.

### ISSUE THREAD

**Issue by MTCodes01** [dualiteindia/.github#4]
**Describe the bug**
I made a home page for a website in figma with dark and light mode switchable, but when i wanted to try it out in code, I used Dualite to convert it to code but the animation.css and style.css shows : /* Some syntax/parsing error in CSS, Please report the bug at Dualite's GitHub Page. */

**CodeSandBox URL**
https://codesandbox.io/embed/y6hyqd?fontsize=14&hidenavigation=1&theme=dark

![Screenshot 2024-02-25 204614](https://github.com/dualiteindia/.github/assets/108288413/e988f7a1-f18d-48c0-89bc-6ee0a4b528e8)

**Comment by prakhart111** [comment]
Hey @MTCodes01, 
I'll need to check on the design you tried. You can drop the link here (preferred), or if the design is private, you can mail it to us at info@dualite.in

As the error msg says, something when wrong while parsing the CSS code. We internally use Prettier to format the CSS, so most probably some syntax error occurred here.

Thanks!

**Comment by MTCodes01** [comment]
I emailed the link to info@dualite.in
The flow that I tried is named **Start_test_1**
pls mention if you encounter any issues in the file access.

**Comment by prakhart111** [comment]
Thanks, do provide me access (ptofficial29@gmail.com) I'll check this out

**Comment by MTCodes01** [comment]
I gave access to ptofficial29@gmail.com .

**Comment by prakhart111** [comment]
Okay I got it, the background image in your hero section ( named image-1 ) had 2 Radial gradients, which was causing some syntax error in the generated CSS, hence the bug.

We'll fix this internally in the next update. 

Also, your design had branched prototypes, code will be generated, but might not behave as expected right now. We're working to bring complete branched support. for your mode-converter switch to work, you can remove the trigger you have on your CTA button.

Thanks!

**Comment by MTCodes01** [comment]
Oh ok, so can I use a single gradient for now? And I am working on making the branched part into a single frame, so will it be ok if I remove one gradient and make all in one frame for now?

**Comment by prakhart111** [comment]
Yes a single one will work. 

If you want your dark-light toggle switch to work in this case, you have to remove this trigger (img below)

![image](https://github.com/dualiteindia/.github/assets/86708181/7ee14a48-795c-4378-8209-591d7e2b5faa)

In case you need something static ( single frame ), detach all triggers and run only one frame. 
Plugin will show "Frame Selected" in this case rather than "Flow Selected"

**Comment by MTCodes01** [comment]
So for prototyping the toggle I just need to remove all triggers and remove one of the gradients.

**Comment by prakhart111** [comment]
No, for toggle to work, just remove the one in image from both frames, just keep the toggle triggers.

**Comment by MTCodes01** [comment]
Oh ok ok 😅, my bad! Understood now 👍
And thanks for helping with the problem, I will mention if there is any other problems.
