### ISSUE TITLE
cannot read property 'id' of null

### ISSUE THREAD

**Issue by brocode101** [dualiteindia/.github#5]
**Describe the bug**
cannot read property 'id' of null

**The link to design file**
Make sure your link is public so that we can access it to test it out. We recommend to make a new file and copy that bug-generating design into it, then share the link
File Link: https://www.figma.com/file/AsNH5XOmOa03WDIOAOxCyT/Interactive-Photography-Landing-Template?type=design&node-id=1%3A5230&mode=design&t=bCz9JAnTm8zFf9Ux-1

**CodeSandBox URL**

**Screenshots**

**Additional context**

**Comment by prakhart111** [comment]
This is resolved now.
